// <auto-generated />
using System;
using Chirp.Razor.DomainModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chirp.Razor.Migrations
{
    [DbContext(typeof(ChirpDbContext))]
    [Migration("20251008130328_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Chirp.Razor.DomainModel.Author", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("username");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Chirp.Razor.DomainModel.Cheep", b =>
                {
                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorusername")
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("timeStamp");

                    b.HasIndex("Authorusername");

                    b.ToTable("Cheeps");
                });

            modelBuilder.Entity("Chirp.Razor.DomainModel.Cheep", b =>
                {
                    b.HasOne("Chirp.Razor.DomainModel.Author", null)
                        .WithMany("cheeps")
                        .HasForeignKey("Authorusername");
                });

            modelBuilder.Entity("Chirp.Razor.DomainModel.Author", b =>
                {
                    b.Navigation("cheeps");
                });
#pragma warning restore 612, 618
        }
    }
}
