// <auto-generated />
using System;
using Chirp.Razor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chirp.Razor.Migrations
{
    [DbContext(typeof(ChirpDbContext))]
    partial class ChirpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Models.Author", b =>
                {
                    b.Property<string>("userame")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userame");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Models.Cheep", b =>
                {
                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authoruserame")
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("timeStamp");

                    b.HasIndex("Authoruserame");

                    b.ToTable("Cheeps");
                });

            modelBuilder.Entity("Models.Cheep", b =>
                {
                    b.HasOne("Models.Author", null)
                        .WithMany("cheeps")
                        .HasForeignKey("Authoruserame");
                });

            modelBuilder.Entity("Models.Author", b =>
                {
                    b.Navigation("cheeps");
                });
#pragma warning restore 612, 618
        }
    }
}
